import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

const env = createEnv({
	server: {
		NODE_ENV: z.enum(["development", "test", "production"]),

		SANITY_ACCESS_TOKEN: z.string(),
		SANITY_COMMERCE_SKU_SYNC_SECRET: z.string().optional(),

		COMMERCE_LAYER_CLIENT_ID: z.string(),
		COMMERCE_LAYER_CLIENT_SECRET: z.string(),
		COMMERCE_LAYER_ORGANIZATION: z.string(),
	},
	client: {
		NEXT_PUBLIC_SITE_URL: z.string().url(),
		NEXT_PUBLIC_SITE_TITLE: z.string().optional(),

		NEXT_PUBLIC_SANITY_PROJECT_ID: z.string(),
		NEXT_PUBLIC_SANITY_PROJECT_TITLE: z.string().optional(),
		NEXT_PUBLIC_SANITY_DATASET: z.enum(["development", "production"]),
		NEXT_PUBLIC_SANITY_API_VERSION: z.string().optional(),
		NEXT_PUBLIC_SANITY_PREVIEW_TOKEN: z.string().optional(),
	},
	runtimeEnv: {
		NODE_ENV: process.env.NODE_ENV,

		SANITY_ACCESS_TOKEN: process.env.SANITY_ACCESS_TOKEN,
		SANITY_COMMERCE_SKU_SYNC_SECRET: process.env.SANITY_COMMERCE_SKU_SYNC_SECRET,

		COMMERCE_LAYER_CLIENT_ID: process.env.COMMERCE_LAYER_CLIENT_ID,
		COMMERCE_LAYER_CLIENT_SECRET: process.env.COMMERCE_LAYER_CLIENT_SECRET,
		COMMERCE_LAYER_ORGANIZATION: process.env.COMMERCE_LAYER_ORGANIZATION,

		NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
		NEXT_PUBLIC_SITE_TITLE: process.env.NEXT_PUBLIC_SITE_TITLE,

		NEXT_PUBLIC_SANITY_PROJECT_ID: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
		NEXT_PUBLIC_SANITY_PROJECT_TITLE: process.env.NEXT_PUBLIC_SANITY_PROJECT_TITLE,
		NEXT_PUBLIC_SANITY_DATASET: process.env.NEXT_PUBLIC_SANITY_DATASET,
		NEXT_PUBLIC_SANITY_API_VERSION: process.env.NEXT_PUBLIC_SANITY_API_VERSION,
		NEXT_PUBLIC_SANITY_PREVIEW_TOKEN: process.env.NEXT_PUBLIC_SANITY_PREVIEW_TOKEN,
	},
});

export { env };
