name: CI
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: "${{ matrix.node }}"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run lint & prettier
        run: "npm run lint:check && npm run format:check"

      - name: Bundle and Output
        env:
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
          SANITY_ACCESS_TOKEN: ${{ secrets.SANITY_ACCESS_TOKEN }}
          COMMERCE_LAYER_CLIENT_ID: ${{ secrets.COMMERCE_LAYER_CLIENT_ID }}
          COMMERCE_LAYER_CLIENT_SECRET: ${{ secrets.COMMERCE_LAYER_CLIENT_SECRET }}
          COMMERCE_LAYER_ORGANIZATION: ${{ secrets.COMMERCE_LAYER_ORGANIZATION }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run build
