name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 16

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '${{ matrix.node }}'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --prefer-offline

      - name: Run lint & prettier
        run: 'yarn lint:check && yarn format:check'
        
      - name: Bundle and Output
        run: |
          touch .env.local
          echo NEXT_PUBLIC_SANITY_PROJECT_DATASET=${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_DATASET }} >> .env.local
          echo NEXT_PUBLIC_SANITY_PROJECT_ID=${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }} >> .env.local
          echo NEXT_PUBLIC_SANITY_API_VERSION=${{ secrets.NEXT_PUBLIC_SANITY_API_VERSION }} >> .env.local
          echo SANITY_API_TOKEN=${{ secrets.SANITY_API_TOKEN }} >> .env.local
          echo SANITY_PREVIEW_TOKEN=${{ secrets.SANITY_PREVIEW_TOKEN }} >> .env.local
          echo SANITY_WEBHOOK_SECRET=${{ secrets.SANITY_WEBHOOK_SECRET }} >> .env.local
          echo CHEC_API_URL=${{ secrets.CHEC_API_URL }} >> .env.local
          echo CHEC_PUBLIC_API_KEY=${{ secrets.CHEC_PUBLIC_API_KEY }} >> .env.local
          echo CHEC_SECRET_API_KEY=${{ secrets.CHEC_SECRET_API_KEY }} >> .env.local
          echo CHEC_WEBHOOK_SIGNING_KEY=${{ secrets.CHEC_WEBHOOK_SIGNING_KEY }} >> .env.local
          echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} >> .env.local
          echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} >> .env.local
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env.local
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env.local
          echo FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }} >> .env.local
          echo FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }} >> .env.local
          echo EMAIL_SERVER_HOST=${{ secrets.EMAIL_SERVER_HOST }} >> .env.local
          echo EMAIL_SERVER_PORT=${{ secrets.EMAIL_SERVER_PORT }} >> .env.local
          echo EMAIL_FROM=${{ secrets.EMAIL_FROM }} >> .env.local
          echo EMAIL_SERVER_USER=${{ secrets.EMAIL_SERVER_USER }} >> .env.local
          echo EMAIL_SERVER_PASSWORD=${{ secrets.EMAIL_SERVER_PASSWORD }} >> .env.local
          echo NEXT_PUBLIC_ALGOLIA_APP_ID=${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }} >> .env.local
          echo NEXT_PUBLIC_ALGOLIA_SEARCH_KEY=${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_KEY }} >> .env.local
          echo ALGOLIA_ADMIN_KEY=${{ secrets.ALGOLIA_ADMIN_KEY }} >> .env.local
          echo ALGOLIA_WEBHOOK_SECRET=${{ secrets.ALGOLIA_WEBHOOK_SECRET }} >> .env.local
          yarn build