name: CI
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: "${{ matrix.node }}"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run lint & prettier
        run: "npm run lint:check && npm run format:check"

      - name: Bundle and Output
        run: npm run build
